defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch={epoch}-val_psnr={val/psnr:.4f}-val_ssim={val/ssim:.4f}"
  monitor: "val/ssim"
  mode: "max"
  save_last: False
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/ssim"
  patience: 10
  mode: "max"

model_summary:
  max_depth: -1
